services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # App default port
      - "5005:5005" # Debug port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sosmedb  # Use port 5432 inside the container
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: developer
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5432"  # Redirect traffic from port 5433 from the host machine to port 5432 from the container
    environment:
      POSTGRES_DB: sosmedb
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
